### ISSUE TITLE
[Documentation] Please describe the way of contributing in a separate file

### ISSUE THREAD

**Issue by Rafalonso** [RiotGames/LoRDeckCodes#1]
Thinking of porting this to python. Need a new root directory under a different name or a separate repository and link it from here?
It's not clear from:

> We have a public C# library on GitHub to demonstrate how to generate and parse a deck codes and will be reviewing pull requests if community contributes implementations in other languages.

**Comment by LarsBaertschi** [comment]
I came across the same question, except my port would be for Java/Kotlin.

**Comment by RiotTuxedo** [comment]
I've had a discussion with the team and we believe the best path forward here will be to create a separate repository with your implementation. We'll be happy to add a reference to your implementation on the README. Thanks for having taken the time to work on another implementation!

https://github.com/RiotGames/LoRDeckCodes#implementations
