### ISSUE TITLE
Version change (1->2 for Bilgewater, 2->3 for Targon) is confusing

### ISSUE THREAD

**Issue by zofrex** [RiotGames/LoRDeckCodes#47]
Commit a27d269ead7f7e0b16b64a77bd2f1c40369498a2 changed the version numbers, and appears to "retcon" Bilgewater from v2 to v1, and change Targon from v3 to v2.

Where this gets confusing is third-party library support - lots of libraries are declaring support for v2 but do not support the Targon faction, because at the time v2 meant Bilgewater (see the table of third party libraries to see what I mean).

If it's a typo it'd be great to have the README clarified, and otherwise I think it would be great – if it's not too late – to bump Targon up to something higher than v2 to avoid confusion with the older version numbers.

**Comment by RiotTuxedo** [comment]
Discussed this internally and we agree. The build is locked for the launch of set 3, but we'll be bumping the version shortly after. I've updated the documentation to reflect this.
