### ISSUE TITLE
The example deck in the readme does not seem to match its description.

### ISSUE THREAD

**Issue by LarsBaertschi** [RiotGames/LoRDeckCodes#6]
When decoding, I get instead of a expected Demacia/Freljord Deck (as described in readme) a Ionia/PiltoverZaun deck. Is the description possibly wrong?

I'm talking about this deck:
`CEAAECABAQJRWHBIFU2DOOYIAEBAMCIMCINCILJZAICACBANE4VCYBABAILR2HRL`

**Comment by RiotTuxedo** [comment]
Yep, this is a remnant of having edited the README just before it went live. I'll update the README accordingly, thanks for the report!
