### ISSUE TITLE
JavaScript port

### ISSUE THREAD

**Issue by pedrofracassi** [RiotGames/LoRDeckCodes#8]
We've ported the library to JavaScript over at https://github.com/SwitchbladeBot/runeterra

Avaliable on NPM at https://www.npmjs.com/package/runeterra

**Comment by Rafalonso** [comment]
I like this better. Can you please provide a PR to link that in README?
I'm curious as to what they prefer since they've been silent on the issue.

**Comment by pedrofracassi** [comment]
What should I name the section? "Third-party ports"?

**Comment by RiotTuxedo** [comment]
Hey all, devs have been pretty heads down making sure the preview patch went smoothly. I'm going to sync with them to see how we want to handle ports to other languages. Thanks for your patience, you all are insanely fast :)

**Comment by RiotTuxedo** [comment]
Alright, I goofed. I've had a discussion with the team and we believe the best path forward here will be to create a separate repository with your implementation. We're concerned that we won't be able to ensure other implementations are properly maintained if they're merged into the C# library. We'll be happy to add a reference to your implementation on the README. It's mostly a miscommunication on my part, so I've gone ahead and updated the Developer Portal [documentation](https://developer.riotgames.com/docs/lor#deck-codes) to properly reflect the best way to contribute additional languages. You all are amazing, thanks for taking the time to contribute an implementation.

https://github.com/RiotGames/LoRDeckCodes#implementations
