### ISSUE TITLE
Index for the Runeterra region (RU) isn't yet known

### ISSUE THREAD

**Issue by CuriouserThing** [RiotGames/LoRDeckCodes#84]
The "integer identifier" for Set 6's new Runeterra region (RU) is currently unknown. App devs need this bit of data ASAP in reveal season to generate valid, shareable/importable deckcodes.

**Comment by RiotTuxedo** [comment]
| Version | Integer Identifier | Faction Identifier | Faction Name |
|---|---|---|---|
| 5 | 12 | RU | Runeterra |
